apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Nabilou-Anoir/Pokemon-V1.git
    targetRevision: main
    path: helm/pokemon-app
    helm:
      parameters:
        - name: image.repository
          value: zouboupe/pokemon-app
        - name: image.tag
          value: "8"

  destination:
    server: https://kubernetes.default.svc
    namespace: pokemon-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
